### PR TITLE
Update gitignore and remove extra files that don't need to be shared.

### PR DESCRIPTION
**Pull request by atroutt**

### CODE REVIEW

**Comment by atroutt** [comment]
@jchunchar and @MatthewPageCS what do you think about this?

**Comment by MatthewPageCS** [comment]
It looks like you removed a lot of stuff from the gitignore.... was this intentional? Won't this start pushing compiled files (like .class and /bin stuff)?

**Comment by jchunchar** [comment]
@atroutt -- you have a much better understanding of the gitignore file than I do, but I agree that we should ignore any auto-generated files with local dirs etc.

**Comment by atroutt** [comment]
Totally agreed with you both, no way do we want generated files in here. 

We were ignoring a lot of things that didn't exist. That being said, erring on the side of more in the .gitignore is fine. I can revert some of that (keeping my additions of .idea and .DS_Store)

**Comment by atroutt** [comment]
Updated!

**Pull request merged**
