### PR TITLE
Put the images in a directory that's private to the app. 

### PR DESCRIPTION
**Pull request by atroutt**
I don't think we generally want to be creating a public SlyceMessaging directory on people's phones.

### CODE REVIEW

**Comment by atroutt** [comment]
@jchunchar @MatthewPageCS what do you think?

**Comment by MatthewPageCS** [comment]
So, Hangouts throws them in a folder called "Hangouts". And FaceBook Messenger just saves it to a folder called "Pictures". Either way, the directory is visible to the user, which is where I got the idea from.

**Comment by atroutt** [comment]
Right, but this isn't hangouts, it's just a library that could be in any old app. I don't want to assume that people are going to want these pictures to be visible outside the app, and even if they do they won't want the folder to be called "SlyceMessaging" :)

**Comment by MatthewPageCS** [comment]
Right, fair enough.

**Pull request merged**
